.TH "WSLUSC" "1" "DATEPLACEHOLDER" "VERSIONPLACEHOLDER" "WSL Utilities User Manual"
.SH NAME
.B wslusc
- Component of WSL Utilities
.SH SYNOPSIS
.B wslusc
.RB [ OPTIONS ]
.I COMMAND
.RI [ ARGUMENTS ...]
.PP
.B wslusc
.B \-d
.I SHORTCUT_FILE
.PP
.B wslusc
.RB [ \-hv ]
.SH DESCRIPTION
This is a WSL shortcut creator to create shortcut on Windows Desktop.
.SH OPTIONS
.TP
.B -h, --help
print a simple help
.TP
.B -v, --version
print current version
.TP
.B -d, --shortcut-debug \fISHORTCUT_FILE\fR
Inspect an existing Windows Desktop shortcut. This mode cannot be combined with shortcut-creation options or COMMAND.
.TP
.B -g, --gui
create a shortcut that links to a GUI application. 
.TP
.B -N, --native
With \fB--gui\fR, launch through wslg.exe. Requires Windows build 21332 or newer.
.TP
.B -i, --icon \fIFILE\fR
Add an icon to the Windows shortcut. Supports \fB.ico\fR, \fB.png\fR, \fB.svg\fR, and \fB.xpm\fR.
.TP
.B -s, --smart-icon
This enables the smart icon detection. This feature requires \'wslpy\' to be installed.
.TP
.B -n, --name \fINAME\fR
add a different name other than the command name.
.TP
.B -e, --env \fIENV\fR
add a custom environment to your command. For example, if you want HiDPI support for a GTK app, add \fBexport GDK_SCALE=2;\fR in your command, like this: \fBwslusc ... \-e "export GDK_SCALE=2;" ...\fR
.TP
.B -I, --interactive
interactive mode.
.SH CONFIGURATION
.TP
.B WSLUSC_GUITYPE
Default GUI type. Default type is 'legacy'. Use 'native' for Native GUI generation (wslg.exe) by default.
.TP
.B WSLUSC_SMART_ICON_DETECTION
Smart Icon Detection. Requires wslpy (Requires Python 3.5). default is \'false\'.
.TP
.B WSLUSC_BASE_CONVERTER_ENGINE
Converter engine. You can choose either 'ffmpeg' or 'imagemagick'. By default it is 'imagemagick'.
.SH AUTHOR
Created by Patrick Wu <me@patrickwu.space>
.SH REPORTING BUGS
Report bugs to <https://github.com/wslutilities/wslu/issues>;
For Ubuntu specific/related bugs, report to <https://bugs.launchpad.net/ubuntu/+source/wslu>.
.SH COPYRIGHT
This is free software; you can redistribute it and/or modify it under
the terms of the GNU GPL version 3 or (at your option) any later
version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
.SH SEE ALSO
wslu(7)